import type { SiteResponse } from "@/lib/api/types";

export const fallbackSite: SiteResponse = {
  siteTitle: "Luminote",
  siteDescription: "Personal Photography Portfolio",
  homeLayout: "editorial",
  watermarkEnabledByDefault: true,
  watermarkText: "© Luminote",
  watermarkPosition: "bottom-right",
  uploadOriginalEnabled: false,
  maxTagPoolSize: 20,
  maxUploadFiles: 20,
  maxTagsPerPhoto: 5,
  photographerAvatarUrl: "",
  photographerName: "",
  photographerBio: "",
  photographerEmail: "",
  photographerXiaohongshu: "",
  photographerXiaohongshuUrl: "",
  photographerDouyin: "",
  photographerDouyinUrl: "",
  photographerInstagram: "",
  photographerInstagramUrl: "",
  photographerCustomAccount: "",
  photographerCustomAccountUrl: "",
};
