import type { SiteResponse } from "@/lib/api/types";

export const fallbackSite: SiteResponse = {
  locale: "zh-CN",
  siteTitle: "Luminote",
  siteDescription:
    "为摄影作品留白，也为灵感片段留一盏灯。",
  homeLayout: "editorial",
  watermarkEnabledByDefault: true,
  watermarkText: "© Luminote",
  watermarkPosition: "bottom-right",
  uploadOriginalEnabled: false,
  maxTotalPhotos: 200,
  maxTagPoolSize: 20,
  maxUploadFiles: 20,
  maxTagsPerPhoto: 5,
  photoMetadataEnabled: true,
  showDateInfo: true,
  showCameraInfo: true,
  showImageInfo: true,
  showAdvancedCameraInfo: true,
  showLocationInfo: true,
  showHistogramInfo: true,
  showDetailedExifInfo: true,
  photographerAvatarUrl: "",
  photographerName: "",
  photographerBio: "",
  photographerEmail: "",
  photographerXiaohongshu: "",
  photographerXiaohongshuUrl: "",
  photographerDouyin: "",
  photographerDouyinUrl: "",
  photographerInstagram: "",
  photographerInstagramUrl: "",
  photographerCustomAccount: "",
  photographerCustomAccountUrl: "",
};
