name = "luminote-api"
main = "src/index.ts"
compatibility_date = "2026-04-02"
workers_dev = true

[vars]
SITE_TITLE = "Luminote"
WATERMARK_ENABLED_BY_DEFAULT = "true"
WATERMARK_TEXT = "Luminote"
CORS_ALLOWED_ORIGINS = "https://luminote-web.pages.dev"
ADMIN_COOKIE_SAME_SITE = "None"
ADMIN_COOKIE_SECURE = "true"

[[d1_databases]]
binding = "DB"
database_name = "luminote-prod"
database_id = "3a982772-65fe-4019-8031-d77a97d1231d"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "luminote-assets"
