export const site = {
  siteTitle: "Luminote",
  siteDescription: "A lightweight home for photography that lets the work breathe.",
  homeLayout: "editorial",
  watermarkEnabledByDefault: true,
  watermarkText: "© Luminote",
  watermarkPosition: "bottom-right",
  uploadOriginalEnabled: false,
  maxTagPoolSize: 20,
  maxUploadFiles: 20,
  maxTagsPerPhoto: 5,
  photographerAvatarUrl: "",
  photographerName: "Luminote",
  photographerBio: "Photographic notes arranged for a portable self-hosted runtime preview.",
  photographerEmail: "",
  photographerXiaohongshu: "",
  photographerXiaohongshuUrl: "",
  photographerDouyin: "",
  photographerDouyinUrl: "",
  photographerInstagram: "",
  photographerInstagramUrl: "",
  photographerCustomAccount: "",
  photographerCustomAccountUrl: "",
};

export const photos = [
  {
    id: "photo_node_001",
    thumbUrl: "/assets/thumb/photo_node_001",
    displayUrl: "/assets/display/photo_node_001",
    watermarkedDisplayUrl: "/assets/display-watermarked/photo_node_001",
    watermarkEnabled: true,
    isHidden: false,
    takenAt: "2026-04-09T08:00:00.000Z",
    description: "Morning facade study",
    tags: ["architecture", "city"],
  },
  {
    id: "photo_node_002",
    thumbUrl: "/assets/thumb/photo_node_002",
    displayUrl: "/assets/display/photo_node_002",
    watermarkedDisplayUrl: "/assets/display-watermarked/photo_node_002",
    watermarkEnabled: true,
    isHidden: false,
    takenAt: "2026-04-08T17:30:00.000Z",
    description: "Late street light",
    tags: ["street", "night"],
  },
  {
    id: "photo_node_003",
    thumbUrl: "/assets/thumb/photo_node_003",
    displayUrl: "/assets/display/photo_node_003",
    watermarkedDisplayUrl: "/assets/display-watermarked/photo_node_003",
    watermarkEnabled: true,
    isHidden: false,
    takenAt: "2026-04-07T13:15:00.000Z",
    description: "Portrait by the window",
    tags: ["portrait", "light"],
  },
  {
    id: "photo_node_004",
    thumbUrl: "/assets/thumb/photo_node_004",
    displayUrl: "/assets/display/photo_node_004",
    watermarkedDisplayUrl: "/assets/display-watermarked/photo_node_004",
    watermarkEnabled: true,
    isHidden: false,
    takenAt: "2026-04-06T11:20:00.000Z",
    description: "Travel notebook frame",
    tags: ["travel", "editorial"],
  },
  {
    id: "photo_node_005",
    thumbUrl: "/assets/thumb/photo_node_005",
    displayUrl: "/assets/display/photo_node_005",
    watermarkedDisplayUrl: "/assets/display-watermarked/photo_node_005",
    watermarkEnabled: true,
    isHidden: false,
    takenAt: "2026-04-05T06:40:00.000Z",
    description: "Bird over the river",
    tags: ["nature", "birds"],
  },
  {
    id: "photo_node_006",
    thumbUrl: "/assets/thumb/photo_node_006",
    displayUrl: "/assets/display/photo_node_006",
    watermarkedDisplayUrl: "/assets/display-watermarked/photo_node_006",
    watermarkEnabled: true,
    isHidden: false,
    takenAt: "2026-04-04T19:05:00.000Z",
    description: "Black and white crossing",
    tags: ["bw", "street"],
  },
];

export const photoDetails = Object.fromEntries(
  photos.map((photo, index) => [
    photo.id,
    {
      ...photo,
      device: "Portable Runtime Camera",
      lens: "50mm f/1.8",
      location: `Node Preview Location ${index + 1}`,
      exif: {
        aperture: "f/1.8",
        shutter: "1/250s",
        iso: 200 + index * 100,
        focalLength: "50mm",
        params: {
          Runtime: "node",
          Preview: "true",
        },
      },
      tags: photo.tags,
    },
  ]),
);

export function listTags() {
  return Array.from(new Set(photos.flatMap((photo) => photo.tags))).sort();
}
